package:
  name: cookiecutter
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

source:
  git_tag: 1.0.0
  git_url: https://github.com/audreyr/cookiecutter.git

build:
  # preserve_egg_dir: True
  entry_points:

    - cookiecutter = cookiecutter.cli:main

  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}

requirements:
  build:
    - python
    - setuptools
    - binaryornot >=0.3.0
    - jinja2 >=2.7
    - pyyaml >=3.10
    - mock
    - click

  run:
    - python
    - binaryornot >=0.3.0
    - jinja2 >=2.7
    - pyyaml >=3.10
    - mock
    - click


test:
  # Python imports
  imports:
    - cookiecutter

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - cookiecutter --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/audreyr/cookiecutter
  license: BSD License
  summary: 'A command-line utility that creates projects from project templates, e.g. creating a Python package project from a Python package project template.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
